server:
  port: 8080

spring:
  application:
    name: hello-world
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
    discovery:
      enabled: true
      service-id: config-server
  profiles:
    active: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/