apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: config-server
    spec:
      containers:
        - image: se24-p08-config-server:latest
          imagePullPolicy: Never        
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:8888/actuator/health || exit 1
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: config-server
          ports:
            - containerPort: 8888
              protocol: TCP
      restartPolicy: Always
