apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hello-world
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: hello-world
    spec:
      containers:
        - image: se24-p08-hello-world:latest
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:8081/actuator/health || exit 1
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: hello-world
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
