apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: eureka-server
    spec:
      containers:
        - image: se24-p08-eureka-server:latest
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:8761/actuator/health || exit 1
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: eureka-server
          ports:
            - containerPort: 8761
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "400m"
            limits:
              memory: "1Gi"
              cpu: "700m"
      restartPolicy: Always
